networks:
  network_app:
    driver: bridge

services:
  app:
    container_name: ${APP_NAME}_app
    hostname: ${APP_NAME}_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/development/node/Dockerfile
      args:
        - UID_HOST_USER=${UID_HOST_USER}
        - GID_HOST_USER=${GID_HOST_USER}
    tty: true
    networks:
      - network_app
    ports:
      - 3333:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.yarn/cache
    environment:
      - UID_HOST_USER=${UID_HOST_USER}
      - GID_HOST_USER=${GID_HOST_USER}
