# docker-compose.development.yml - Staging/Development server environment
# Usage: docker compose -f docker-compose.yml -f docker-compose.development.yml up -d

services:
  app:
    container_name: ${APP_NAME}_dev_app
    hostname: ${APP_NAME}_dev_app
    build:
      context: .
      dockerfile: .docker/development/node/Dockerfile
      args:
        - UID_HOST_USER=${UID_HOST_USER:-1000}
        - GID_HOST_USER=${GID_HOST_USER:-1000}
    tty: true
    ports:
      - "3333:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.yarn/cache
    environment:
      - NODE_ENV=development
    env_file:
      - .env
      - .env.development
