networks:
  network_app:
    driver: bridge

services:
  app:
    container_name: ${APP_NAME}_prod_app
    hostname: ${APP_NAME}_prod_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/production/node/Dockerfile
    env_file:
      - .env
    networks:
      - network_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
