/**
 * Shared authentication error codes and related utilities.
 */

export const AUTH_ERROR_CODES = {
	MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
	INVALID_EMAIL: "INVALID_EMAIL",
	INVALID_PASSWORD: "INVALID_PASSWORD",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	CREDENTIALS_SIGNIN: "CredentialsSignin",
	SESSION_ERROR: "SESSION_ERROR",
	EMAIL_EXISTS: "EMAIL_EXISTS",
	INVALID_NAME: "INVALID_NAME",
} as const;

export const AUTH_SERVICE_ERROR_CODES = {
	MISSING_CREDENTIALS: AUTH_ERROR_CODES.MISSING_CREDENTIALS,
	INVALID_EMAIL: AUTH_ERROR_CODES.INVALID_EMAIL,
	INVALID_PASSWORD: AUTH_ERROR_CODES.INVALID_PASSWORD,
	INVALID_CREDENTIALS: AUTH_ERROR_CODES.INVALID_CREDENTIALS,
	INTERNAL_ERROR: AUTH_ERROR_CODES.INTERNAL_ERROR,
	EMAIL_EXISTS: AUTH_ERROR_CODES.EMAIL_EXISTS,
	INVALID_NAME: AUTH_ERROR_CODES.INVALID_NAME,
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
export type AuthServiceErrorCode =
	(typeof AUTH_SERVICE_ERROR_CODES)[keyof typeof AUTH_SERVICE_ERROR_CODES];

export const AUTH_ERROR_MESSAGE_IDS: Record<AuthErrorCode, string> = {
	[AUTH_ERROR_CODES.MISSING_CREDENTIALS]: "pages.login.invalidCredentials",
	[AUTH_ERROR_CODES.INVALID_EMAIL]: "pages.login.validation.invalidEmail",
	[AUTH_ERROR_CODES.INVALID_PASSWORD]: "pages.login.validation.passwordMinLength",
	[AUTH_ERROR_CODES.INVALID_CREDENTIALS]: "pages.login.invalidCredentials",
	[AUTH_ERROR_CODES.INTERNAL_ERROR]: "pages.login.generalError",
	[AUTH_ERROR_CODES.CREDENTIALS_SIGNIN]: "pages.login.invalidCredentials",
	[AUTH_ERROR_CODES.SESSION_ERROR]: "pages.login.generalError",
	[AUTH_ERROR_CODES.EMAIL_EXISTS]: "pages.register.emailExists",
	[AUTH_ERROR_CODES.INVALID_NAME]: "pages.register.validation.nameRequired",
} as const;
